name: min_chat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'


dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  form_validator: ^2.1.1
  gap: ^3.0.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable:
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  redacted: ^1.0.11
  shared_preferences: ^2.2.2
  toastification: ^1.1.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator:
  injectable_generator:

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - .env
